// <auto-generated />
using HelpDeskLogin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HelpDeskLogin.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181024214816_update6")]
    partial class update6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HelpDeskLogin.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Nome");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("HelpDeskLogin.Models.categorias", b =>
                {
                    b.Property<int>("idCategoria")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ativo");

                    b.Property<string>("categoria");

                    b.Property<string>("descricao");

                    b.HasKey("idCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("HelpDeskLogin.Models.chamados", b =>
                {
                    b.Property<int>("idChamado")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DH_Abertura");

                    b.Property<DateTime>("DH_Fechamento");

                    b.Property<int>("categoriasId");

                    b.Property<int>("comentariosId");

                    b.Property<string>("descricao");

                    b.Property<int>("gruposId");

                    b.Property<int>("logsId");

                    b.Property<int>("prioridadesId");

                    b.HasKey("idChamado");

                    b.HasIndex("categoriasId");

                    b.HasIndex("comentariosId");

                    b.HasIndex("gruposId");

                    b.HasIndex("logsId");

                    b.HasIndex("prioridadesId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("HelpDeskLogin.Models.comentarios", b =>
                {
                    b.Property<int>("idComentario")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DHComentario");

                    b.Property<string>("comentario");

                    b.HasKey("idComentario");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("HelpDeskLogin.Models.grupos", b =>
                {
                    b.Property<int>("idGrupo")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ativo");

                    b.Property<string>("descricao");

                    b.Property<string>("grupo");

                    b.HasKey("idGrupo");

                    b.ToTable("grupos");
                });

            modelBuilder.Entity("HelpDeskLogin.Models.logs", b =>
                {
                    b.Property<int>("idLog")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Log");

                    b.HasKey("idLog");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("HelpDeskLogin.Models.prioridades", b =>
                {
                    b.Property<int>("idPrioridade")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("ativo");

                    b.Property<string>("descricao");

                    b.Property<string>("prioridade");

                    b.HasKey("idPrioridade");

                    b.ToTable("Prioridades");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HelpDeskLogin.Models.chamados", b =>
                {
                    b.HasOne("HelpDeskLogin.Models.categorias", "categorias")
                        .WithMany("chamados")
                        .HasForeignKey("categoriasId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HelpDeskLogin.Models.comentarios", "comentarios")
                        .WithMany("chamados")
                        .HasForeignKey("comentariosId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HelpDeskLogin.Models.grupos", "grupos")
                        .WithMany()
                        .HasForeignKey("gruposId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HelpDeskLogin.Models.logs", "logs")
                        .WithMany("chamados")
                        .HasForeignKey("logsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HelpDeskLogin.Models.prioridades", "prioridades")
                        .WithMany("chamados")
                        .HasForeignKey("prioridadesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HelpDeskLogin.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HelpDeskLogin.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HelpDeskLogin.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HelpDeskLogin.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
